# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{993647b8-142c-4c13-b529-fed97f79939b}',
        'contract_ids': ['@mozilla.org/dom/cross-origin-storage-service;1'],
        'type': 'mozilla::dom::CrossOriginStorageService',
        'headers': ['/dom/crossoriginstorage/CrossOriginStorageService.h'],
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
