/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef mozilla_dom_CrossOriginStoragePublicHashList_h
#define mozilla_dom_CrossOriginStoragePublicHashList_h

#include <cstdint>

#include "CrossOriginStorageUtils.h"
#include "nsStringFwd.h"

namespace mozilla::dom {

// https://wicg.github.io/cross-origin-storage/#availability-gating
// The Public Hash List half of wildcard-scope's privacy gate (GREASE'ing,
// the other half, is CrossOriginStorageGrease below): a resource whose
// hash is listed here is safe to disclose to any requesting origin
// unconditionally, since its content is by definition already public and
// independently verifiable.
//
// Backed by data/public-hash-list.bin, a real snapshot (~295k SHA-256
// digests) generated by generate_public_hash_list.py from
// https://github.com/WICG/cross-origin-storage's own
// public-hash-list/implementation pipeline -- see that repository's
// public-hash-list/implementation/README.md for how entries qualify
// (k-anonymity-gated real-world popularity: CDN request volume, npm
// downloads, cross-CDN byte-identity, or browser-vendor vetting) and
// generate_public_hash_list.py's own header comment for regeneration
// instructions. Loaded lazily and held resident for the process
// lifetime (~9 MiB) on first Contains() call; not refreshed at runtime
// -- picking up a newer snapshot means re-running the generator and
// rebuilding, matching Ladybird's own "bundled seed resource, periodic
// refresh out of scope" choice for the same gate.
class CrossOriginStoragePublicHashList {
 public:
  static bool Contains(COSHashAlgorithm aAlgorithm,
                       const nsACString& aValueHex);
};

// https://wicg.github.io/cross-origin-storage/#grease
// An independent, randomized, size-capped chance of disclosure for
// wildcard-scoped entries not on the Public Hash List, so a requesting
// origin can never distinguish "not on the PHL" from "not GREASE'd this
// particular request" by retrying -- both must look identically like an
// ordinary not-found. Probability and size ceiling match Servo's and
// Ladybird's own chosen constants (neither is spec-mandated).
class CrossOriginStorageGrease {
 public:
  static bool ShouldDisclose(uint64_t aByteSize);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_CrossOriginStoragePublicHashList_h
